# Permalinks
permalink:        pretty

# Setup
title:            HITO
tagline:          'A Health IT Ontology'
description:      'A Health IT Ontology for systematically describing application systems and software products in health IT. By <a href="https://imise.uni-leipzig.de/" target="_blank">IMISE</a> and <a href="https://umit.at/" target="_blank">UMIT</a>.'
url:              https://hitontology.github.io/
baseurl:          /hitontology.eu/
logo:

author:
  name:           'Konrad HÃ¶ffner & Thomas Pause'
  url:            https://github.com/KonradHoeffner , https://github.com/ThomasPause

# Custom vars
version:          0.0.1

github:
  org:           https://github.com/hitontology

socialmedia:
  twitter: https://twitter.com/hitontology

internal:
  owncloud:  https://denethor.imise.uni-leipzig.de/index.php/apps/files?dir=/Shared/HITO/
  slack:     https://hito-project.slack.com/

links:
  imise:     https://imise.uni-leipzig.de/
  umit:      https://umit.at/
  winter:    http://www.people.imise.uni-leipzig.de/alfred.winter/
  ammenwerth: https://www.umit.at/page.cfm?vpath=departments/technik/iig/

plugins:
